spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:3306/banka_db
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=XYhQIyrLxBkRvSHEOteshj73LEI+kFFM0l4gclwCIq8=
jwt.expiration=3600000
